fragaria.datacite:
  type: config_object
  label: 'Fragaria Datacite Settgings'
  mapping:
    active:
      type: boolean
      label: 'If DataCite API Integration is active'
    use_do_url:
      type: boolean
      label: 'If URLs sent to DataCite will be always /do/{uuid}. Recommended! Up to the user to keep, either the aliases OR enable the DO workaround in this module'
    repository_fabrica_user:
      type: string
      label: "DataCite Repository User"
    repository_fabrica_password:
      type: string
      label: "DataCite Repository Passowrd"
    doi_prefix:
      type: string
      label: "The DOI Prefix assigned to your Institution and associated to your credentials"
    use_test_account:
      type: boolean
      label: 'If DataCite API Integration should interact against DataCites Staging server'
    repository_fabrica_user_test:
      type: string
      label: "DataCite Test Account User"
    repository_fabrica_password_test:
      type: string
      label: "DataCite Test Account Passowrd"
    processor_entity_id:
      type: string
      label: "Uuid of the Metadata Display used to Cast DataCite valid metadata"
fragaria.fragariaredirect_entity.*:
  type: config_entity
  label: 'Fragaria Redirect Config Entity'
  mapping:
    uuid:
      type: string
    langcode:
      type: string
    status:
      type: boolean
    id:
      type: string
      label: 'ID'
    label:
      type: string
      label: 'Label'
    path_prefixes:
      type: sequence
      label: 'Path Prefixes'
      sequence:
        - type: string
    search_api_index:
      type: string
      label: 'Search API Index'
    search_api_field:
      type: string
      label: 'Saerch API Field'
    path_suffixes:
      type: sequence
      label: 'Path Suffixes'
      sequence:
        - type: string
    search_api_field_value_prefixes:
      type: sequence
      label: 'search api field value prefixes'
      sequence:
        - type: string
    search_api_field_value_suffixes:
      type: sequence
      label: 'search api field value Suffixes'
      sequence:
        - type: string
    variable_path_suffix:
      type: boolean
      label: 'Variable Path Suffix'
    redirect_http_code:
      type: string
      label: 'Redirect HTTP Code'
    cache:
      type: boolean
      label: 'Cached'
    active:
       type: boolean
       label: 'Active'
    do_replacement:
      type: boolean
      label: 'If do/UUID replacement is added'
    segments_in_pattern:
      type: sequence
      label: 'Segments of the exposed URL to be sent against search API'
      sequence:
        - type: string
    custom_404:
      type: string
      label: 'A valid relative path for 404 responses. Leave empty for the default'
    allow_empty_variable:
      type: boolean
      label: 'If the Route Path (without suffixes) allows to be called without the variable part'