<?php

namespace Drupal\fragaria\Plugin\WebformElement;

use Drupal\Core\Form\FormStateInterface;
use Drupal\fragaria\DataCiteService;
use Drupal\webform\Entity\WebformOptions;
use Drupal\webform\Utility\WebformArrayHelper;
use Drupal\webform\Plugin\WebformElement\OptionsBase;
use Drupal\webform\WebformSubmissionInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Provides a DOI Minting 'select' element.
 *
 * @WebformElement(
 *   id = "webform_fragaria_datacite_doi",
 *   api = "https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Render!Element!Select.php/class/Select",
 *   label = @Translation("DOI Minting and Updates"),
 *   description = @Translation("Provides a form element to Manage DataCite DOIs."),
 *   category = @Translation("Options elements"),
 * )
 */
class FragariaDataCite extends OptionsBase {

  /**
   * @var \Drupal\Fragaria\DataCiteService
   */
  private DataCiteService $dataCiteService;


  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition) {
    $instance = parent::create($container, $configuration, $plugin_id, $plugin_definition);
    $instance->dataCiteService = $container->get('fragaria.datacite');
    return $instance;
  }

  /**
   * {@inheritdoc}
   */
  protected function defineDefaultProperties() {
    $properties = [
        // Options settings.
        'empty_option' => 'No DOI',
        'empty_value' => '',
        'sort_options' => FALSE,
        'select2' => FALSE,
        'choices' => FALSE,
        'chosen' => FALSE,
        'placeholder' => '',
        'help_display' => '',
        'doi_id' => NULL,
        'doi_status' => NULL,
        'size' => '',
        'store' => FALSE,
        'options' => [
          'Draft a DOI' => 'draft',
          'Register DOI' => 'register',
          'Publish DOI (findable)' => 'publish',
          'Delete a Draft DOI' => 'delete'
        ],
      ] + parent::defineDefaultProperties();
    unset($properties['multiple']);
    unset($properties['multiple_error']);
    return $properties;
  }

  /* ************************************************************************ */

  /**
   * {@inheritdoc}
   */
  public function supportsMultipleValues() {
    return FALSE;
  }

  /**
   * @inheritDoc
   */
  public function initialize(array &$element) {
    parent::initialize($element); // TODO: Change the autogenerated stub
    // We need fixed options here

    $element['#options'] = [
      'draft' => 'Draft a DOI',
      'register' => 'Register DOI',
      'publish' => 'Publish DOI (findable)',
      'delete' => 'Delete a Draft DOI'
    ];

  }

  /**
   * {@inheritdoc}
   */
  public function prepare(array &$element, WebformSubmissionInterface $webform_submission = NULL) {
    $config = $this->configFactory->get('webform.settings');

    // Always include empty option.
    // Note: #multiple select menu does support empty options.
    // @see \Drupal\Core\Render\Element\Select::processSelect
    if (!isset($element['#empty_option']) && empty($element['#multiple'])) {
      $required = isset($element['#states']['required']) ? TRUE : !empty($element['#required']);
      $empty_option = $required
        ? ($config->get('element.default_empty_option_required') ?: $this->t('- Select -'))
        : ($config->get('element.default_empty_option_optional') ?: $this->t('- None -'));
      if ($config->get('element.default_empty_option')) {
        $element['#empty_option'] = $empty_option;
      }
      // Copied from: \Drupal\Core\Render\Element\Select::processSelect.
      elseif (($required && !isset($element['#default_value'])) || isset($element['#empty_value'])) {
        $element['#empty_option'] = $empty_option;
      }
    }

    // Attach library which allows options to be disabled via JavaScript.
    $element['#attached']['library'][] = 'webform/webform.element.select';
    //NOTE EMPTY OPTION IS NOT RESPECTED HERE.
    parent::prepare($element, $webform_submission);
    // Handle Conditional Options based on existing Submitted values.
    if ($this->dataCiteService->isActive()) {
      $api = $this->dataCiteService->getActiveAPI();
      $original_data = $webform_submission->getOriginalData();
      $datacite_value = $original_data['ap:tasks']['ap:fragaria'][$api] ?? NULL;
      if (!empty($datacite_value)) {
        // Validate it
        $validated = $this->dataCiteService->validateApTask($datacite_value);
        if ($validated['valid'] && $validated['status'] && $validated['doi']) {
              $element['#empty_option'] = $this->t(' -- Keep DOI Status -- ');
              $element['#doi_id'] = $validated['doi'];
              $element['#doi_status'] = $validated['status'];
              $element['#doi_api'] = $api;
              if ($validated['status'] == "draft") {
                unset($element['#options']['draft']);
              }
              elseif ($validated['status'] == "registered") {
                unset($element['#options']['draft']);
                unset($element['#options']['delete']);
              }
              elseif ($validated['status'] == "findable") {
                unset($element['#options']['draft']);
                unset($element['#options']['delete']);
                unset($element['#options']['publish']);
              }
        }
        else {
          // Invalid state. Set a message in the description but allow any new values
          // As if minting again.
        }
      }
      else {
        $this->t(' -- NO DOI -- ');
        unset($element['#options']['delete']);
      }
      // we need ap:tasks key holding our precious!

    }
    else {
      // If dataCiteService is disabled, disable too
      $element['#access'] = FALSE;
    }




  }

  /**
   * {@inheritdoc}
   */
  public function form(array $form, FormStateInterface $form_state) {
    $form = parent::form($form, $form_state);
    unset($form['options']);
    unset($form['options_other']);
    unset($form['options_properties']);

    // Add states to placeholder if custom library is supported and the
    // select menu supports multiple values.
    $placeholder_states = [];
    if ($placeholder_states) {
      $form['form']['placeholder']['#states']['visible'] = [
        [
          ':input[name="properties[multiple][container][cardinality]"]' => ['value' => 'number'],
          ':input[name="properties[multiple][container][cardinality_number]"]' => ['!value' => 1],
        ],
        $placeholder_states,
      ];
    }
    else {
      $form['form']['placeholder']['#access'] = FALSE;
    }

    // Update multiple select size property.
    $form['form']['size_container']['size']['#description'] = $this->t('Specifies the number of visible options.');
    $form['form']['size_container']['#states'] = [
      'visible' => [
        ':input[name="properties[multiple][container][cardinality_number]"]' => ['!value' => 1],
      ],
    ];

    return $form;
  }

  /**
   * @inheritDoc
   */
  public function preSave(array &$element, WebformSubmissionInterface $webform_submission) {
    // Remove all captcha related keys from the webform submission's data.
    $key = $element['#webform_key'];
    $data = $webform_submission->getData();
    if (($data[$key] ?? "") !== "" && ($element['#access'] ?? TRUE)) {
      if ($this->dataCiteService->isActive()) {
        $api = $this->dataCiteService->getActiveAPI();
        $original_data = $webform_submission->getOriginalData();
        $datacite_value = $original_data['ap:tasks']['ap:fragaria'][$api] ?? NULL;
        $validated = $this->dataCiteService->validateApTask($datacite_value);
        if ($validated['valid']) {
          $datacite_value['event'] = $data[$key];
          $data['ap:tasks']['ap:fragaria'][$api] = $datacite_value;
        }
        else {
          unset($datacite_value['event']);
          $data['ap:tasks']['ap:fragaria'][$api] = $datacite_value;
        }
      }
    }
    unset($data[$key]);
    $webform_submission->setData($data);
  }
}
